06-producer-portal/code/main/default/unpackaged/objects/Producer_Placed_on_Market__c.object
<CustomObject>
</CustomObject>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Producer Placed on Markets</relationshipLabel>
    <relationshipName>Producer_Placed_on_Markets</relationshipName>
    <type>Lookup</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Acknowledgement_of_Statements__c.field-meta.xml
<CustomField>
    <fullName>Acknowledgement_of_Statements__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Acknowledgement of Statements</label>
    <type>Checkbox</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_10_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_10_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Automatic dispensers</inlineHelpText>
    <label>Category 10 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_10_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_10_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Automatic dispensers</inlineHelpText>
    <label>Category 10 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_11_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_11_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Display equipment</inlineHelpText>
    <label>Category 11 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_11_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_11_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Display equipment</inlineHelpText>
    <label>Category 11 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_12_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_12_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Appliances containing refrigerants</inlineHelpText>
    <label>Category 12 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_12_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_12_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Appliances containing refrigerants</inlineHelpText>
    <label>Category 12 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_13_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_13_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Gas discharge lamps and light-emitting diode (LED) light sources</inlineHelpText>
    <label>Category 13 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_13_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_13_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Gas discharge lamps and light-emitting diode (LED) light sources</inlineHelpText>
    <label>Category 13 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_14_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_14_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>PV panels (solar panels)</inlineHelpText>
    <label>Category 14 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_14_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_14_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>PV panels (solar panels)</inlineHelpText>
    <label>Category 14 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_15_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_15_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Vapes and electronic cigarettes</inlineHelpText>
    <label>Category 15 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_1_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_1_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Large household appliances</inlineHelpText>
    <label>Category 1 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_1_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_1_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Large appliances</inlineHelpText>
    <label>Category 1 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_2_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_2_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Small household appliances</inlineHelpText>
    <label>Category 2 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_2_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_2_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Small appliances</inlineHelpText>
    <label>Category 2 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_3_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_3_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>IT and telecommunications equipment</inlineHelpText>
    <label>Category 3 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_3_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_3_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>IT and telecommunications equipment</inlineHelpText>
    <label>Category 3 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_4_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_4_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Consumer equipment</inlineHelpText>
    <label>Category 4 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_4_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_4_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Consumer equipment</inlineHelpText>
    <label>Category 4 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_5_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_5_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Lighting equipment</inlineHelpText>
    <label>Category 5 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_5_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_5_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Lighting equipment</inlineHelpText>
    <label>Category 5 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_6_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_6_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Electrical and electronic tools (except large scale stationary industrial tools)</inlineHelpText>
    <label>Category 6 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_6_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_6_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Electrical and electronic tools (except large scale stationary industrial tools)</inlineHelpText>
    <label>Category 6 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_7_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_7_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Toys, leisure and sports equipment</inlineHelpText>
    <label>Category 7 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_7_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_7_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Toys, leisure and sports equipment</inlineHelpText>
    <label>Category 7 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_8_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_8_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Medical devices (except implanted and infected products)</inlineHelpText>
    <label>Category 8 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_8_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_8_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Medical devices (except implanted and infected products)</inlineHelpText>
    <label>Category 8 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_9_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_9_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Monitoring and control equipment</inlineHelpText>
    <label>Category 9 Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Category_9_Non_Household__c.field-meta.xml
<CustomField>
    <fullName>Category_9_Non_Household__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Monitoring and control equipment</inlineHelpText>
    <label>Category 9 Non-Household</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Compliance_Year__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Year__c</fullName>
    <label>Compliance Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

06-producer-portal/code/main/default/objects/Producer_Placed_on_Market__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Auto-calculated status field that provides granular status indicators for Producer Portal users. Updated by the Producer POM - Update Status flow.</description>
    <inlineHelpText>Current status of this POM record. This field is automatically updated based on acknowledgement, questions, and signature status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for Market Data</fullName>
                <default>true</default>
                <label>Waiting for Market Data</label>
            </value>
            <value>
                <fullName>Ready to Acknowledge</fullName>
            </value>
            <value>
                <fullName>Acknowledge Market Data</fullName>
            </value>
            <value>
                <fullName>Questions Required</fullName>
            </value>
            <value>
                <fullName>Pending Director Review</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

06-producer-portal/code/main/default/classes/ProducerPomAcknowledgeControllerTest.cls
@isTest
private class ProducerPomAcknowledgeControllerTest {

    @isTest
    static void testGetRecordStatus() {
        // Create test account
        Account acc = new Account(
            Name = 'Test Account',
            comp_house__Company_Number__c = '12345678'
        );
        insert acc;

        // Create test Producer POM record
        Producer_Placed_on_Market__c pom = new Producer_Placed_on_Market__c(
            Account__c = acc.Id,
            Quarter__c = 'Q1',
            Compliance_Year__c = '2025',
            Acknowledgement_of_Statements__c = false
        );
        insert pom;

        // Test the controller method
        Test.startTest();
        Map<String, Object> result = ProducerPomAcknowledgeController.getRecordStatus(pom.Id);
        Test.stopTest();

        // Verify results
        System.assertEquals(true, result.get('success'), 'Should succeed');
        System.assertNotEquals(null, result.get('shouldShowPopup'), 'Should return shouldShowPopup value');
    }

    @isTest
    static void testGetRecordStatusInvalidId() {
        // Test with invalid record ID
        Test.startTest();
        Map<String, Object> result = ProducerPomAcknowledgeController.getRecordStatus('invalid');
        Test.stopTest();

        // Verify error handling
        System.assertEquals(false, result.get('success'), 'Should fail with invalid ID');
        System.assertNotEquals(null, result.get('error'), 'Should return error message');
    }

    @isTest
    static void testGetNextActions() {
        // Create test account
        Account acc = new Account(
            Name = 'Test Account',
            comp_house__Company_Number__c = '12345678'
        );
        insert acc;

        // Create test Producer POM record
        Producer_Placed_on_Market__c pom = new Producer_Placed_on_Market__c(
            Account__c = acc.Id,
            Quarter__c = 'Q1',
            Compliance_Year__c = '2025',
            Status__c = 'Acknowledge Market Data',
            Category_1_Household__c = 100,
            Category_2_Household__c = 100,
            Category_3_Household__c = 100,
            Category_4_Household__c = 100,
            Category_5_Household__c = 100,
            Category_6_Household__c = 100,
            Category_7_Household__c = 100,
            Category_8_Household__c = 100,
            Category_9_Household__c = 100,
            Category_10_Household__c = 100,
            Category_11_Household__c = 100,
            Category_12_Household__c = 100,
            Category_13_Household__c = 100,
            Category_14_Household__c = 100,
            Category_15_Household__c = 100,
            Category_1_Non_Household__c = 100,
            Category_2_Non_Household__c = 100,
            Category_3_Non_Household__c = 100,
            Category_4_Non_Household__c = 100,
            Category_5_Non_Household__c = 100,
            Category_6_Non_Household__c = 100,
            Category_7_Non_Household__c = 100,
            Category_8_Non_Household__c = 100,
            Category_9_Non_Household__c = 100,
            Category_10_Non_Household__c = 100,
            Category_11_Non_Household__c = 100,
            Category_12_Non_Household__c = 100,
            Category_13_Non_Household__c = 100,
            Category_14_Non_Household__c = 100,
            Category_15_Non_Household__c = 100,
            Acknowledgement_of_Statements__c = true
        );
        insert pom;

        // Test the controller method
        Test.startTest();
        Map<String, Object> result = ProducerPomAcknowledgeController.getNextActions(pom.Id);
        Test.stopTest();

        // Verify results
        System.assertEquals(true, result.get('success'), 'Should succeed');
        System.assertNotEquals(null, result.get('isDirector'), 'Should return isDirector value');
        System.assertNotEquals(null, result.get('status'), 'Should return status');
    }
}